# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c269121581b5564cec62b14e6c41f1d156bbb8f4c75408c68ab39fdf6509ff840993796a9286156bc9ee4aceb328a9201ee0b86fa1eac34bf19e7aa60a276eda

test:
  secret_key_base: 20e81d2473879a478b93efeb3b67c85b9987594e6e77d6ccd0f269df6b443f5d7be95f9bbec1acce03e2388be76f9bba667460231bb23dac32df38c8b0072cf3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
